import "./globals.css";
import { ReactNode } from "react";

export const metadata = {
  title: "My Awesome Site",
  description: "Generated by Next.js",
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className="bg-gray-900 text-white font-sans">{children}</body>
    </html>
  );
}
