// /app/layout.js
import "./globals.css";

export const metadata = {
  title: "My Awesome Site",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gray-900 text-white font-sans">{children}</body>
    </html>
  );
}
